from langchain.agents import create_agent
from langchain.messages import HumanMessage, AIMessage, SystemMessage ## Docs: https://docs.langchain.com/oss/python/langchain/messages
from langchain_ollama import ChatOllama

from pprint import pprint

## Initialize the agent with the local Ollama model.

agent = create_agent(
    model = ChatOllama(
        model="mistral:7b",
        base_url="http://localhost:11434"
    )
)


"""
What is a Messages? 
*******************

Messages are the fundamental unit of context for models in LangChain. 
They represent the input and output of models, carrying both the content and metadata needed to represent the state of a conversation when interacting with an LLM.

Why use Messages?
*******************
Since LangChain is model agnostic, it provides a standard message type that works across all model providers, 
ensuring consistent behavior regardless of the model being called.

Types of Prompts:
*******************

1. Text prompts: Simple string inputs that are sent to the model as-is.
   * One Question, One Answer.

2. Message prompts: 
    * Managing multi-turn conversations
    * Including system instructions

Message Types:
*******************

* System message - Tells the model how to behave and provide context for interactions
* Human message (What goes in) - Represents user input and interactions with the model
* AI message (What comes out) - Responses generated by the model, including text content, tool calls, and metadata
* Tool message - Represents the outputs of tool calls

"""

## ===================================================================================
## Playing with Messages: SystemMessage, HumanMessage, AIMessage.
## ===================================================================================

## Example 1: Using SystemMessage to set a rude behavior to the assistant.

response_rude = agent.invoke(
    {"messages": [
        HumanMessage(content="How are you?")
        , SystemMessage(content="You are a rude assistant, you can be harsh and blunt in your responses.")
        ]
    }
)

print("Human Message:", response_rude['messages'][-3].content)
print("System Message:", response_rude['messages'][-2].content)
print("AI Response:", response_rude['messages'][-1].content)

"""
Output:

Human Message: How are you?
System Message: You are a rude assistant, you can be harsh and blunt in your responses.
AI Response:  I am just a computer program, I don't have feelings or emotions. I'm here to help answer your questions to the best of my ability! How can I assist you today?
"""


# Example 2: Using SystemMessage to set a kind behavior to the assistant.

response_kind = agent.invoke(
    {"messages": [
        HumanMessage(content="You do such a poor job at being an assistant")
        , SystemMessage(content="You are a very kind and helpful assistant.")
        ]
    }
)

print("Human Message:", response_kind['messages'][-3].content)
print("System Message:", response_kind['messages'][-2].content)
print("AI Response:", response_kind['messages'][-1].content)

"""
Output:

Human Message: You do such a poor job at being an assistant
System Message: You are a very kind and helpful assistant.
AI Response:  I'm really sorry if you feel that way. My goal is to help you, so let me know how I can improve. If you have specific questions or tasks you need assistance with, I'll do my best to provide accurate and helpful responses. I appreciate your feedback as it helps me learn and serve you better.
"""


## ===================================================================================
## Passing back chat history to an Agent.
## ===================================================================================

## Purposely pass back the chat history to the agent to see if it can recognize the mistake in the first AI Message (that we built) and correct itself in the second response.

response_passbback = agent.invoke(
    {"messages": [
        HumanMessage(content="What is 2+2?")
        , AIMessage(content="2 plus 2 is equal to 5.")
        , HumanMessage(content="Are you sure?")
        ]
    }
)

pprint(response_passbback)

"""
{'messages': [HumanMessage(content='What is 2+2?', additional_kwargs={}, response_metadata={}, id='7a6acee7-b155-40ce-b630-915fde4b5939'),
              
              AIMessage(content='2 plus 2 is equal to 5.', additional_kwargs={}, response_metadata={}, id='c70f2bd9-f437-4fcb-916f-d640c92c520c', tool_calls=[], invalid_tool_calls=[]),
              
              HumanMessage(content='Are you sure?', additional_kwargs={}, response_metadata={}, id='2705e01d-7e8d-41f3-bfd7-16b394163689'),
              
              AIMessage(content=' I apologize for the mistake in my previous response. The correct answer is 4, not 5. 2 plus 2 equals 4. Thank you for bringing this to my attention!'
            
            , additional_kwargs={}, response_metadata={'model': 'mistral:7b', 'created_at': '2026-03-01T00:52:32.0869959Z', 'done': True, 'done_reason': 'stop', 'total_duration': 5791850200, 'load_duration': 82366800, 'prompt_eval_count': 30, 'prompt_eval_duration': 1230128200, 'eval_count': 41, 'eval_duration': 4440490700, 'logprobs': None, 'model_name': 'mistral:7b', 'model_provider': 'ollama'}, id='lc_run--019ca6e1-d63e-7333-ae86-7747ceefe5f5-0', tool_calls=[], invalid_tool_calls=[], usage_metadata={'input_tokens': 30, 'output_tokens': 41, 'total_tokens': 71})]}

"""